### ISSUE TITLE
matplotlib version

### ISSUE THREAD

**Issue by igorandreoni** [growth-astro/growth-school-2020#5]
It would be good to change the matplotlib version from 3.3.0 (current) to 3.2.2 because of some incompatibility with the astroplan. @stevenstetzler Could you please take care of this change and build the new docker image?

**Comment by stevenstetzler** [comment]
I've updated the matplotlib version in the Dockerfile, built, and pushed to the Dockerhub.

Built from Dockerfile:
```
$ docker run -it growthastro/growth-school-2020-notebook:deploy python -c "import matplotlib; print(matplotlib.__version__)"
3.2.2
```

From the hub:
```
$ python -c "import matplotlib; print(matplotlib.__version__)"
3.2.2
```

I made a PR to update the Dockerfile in this repo: https://github.com/growth-astro/growth-school-2020/pull/6
